/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.interfazG;

/**
 *
 * @author Administrator
 */
public class InterfazMenu extends javax.swing.JFrame {

    /**
     * Creates new form interfazMenu
     */
    public InterfazMenu() {
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        salirButtom = new javax.swing.JButton();
        mostrarButtom = new javax.swing.JButton();
        eliminarButtom = new javax.swing.JButton();
        actualizarButtom = new javax.swing.JButton();
        insertarButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salirButtom.setBackground(new java.awt.Color(0, 102, 255));
        salirButtom.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        salirButtom.setForeground(new java.awt.Color(255, 255, 255));
        salirButtom.setText("SALIR");
        salirButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtomActionPerformed(evt);
            }
        });
        jPanel2.add(salirButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 90, -1));

        mostrarButtom.setBackground(new java.awt.Color(0, 102, 255));
        mostrarButtom.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        mostrarButtom.setForeground(new java.awt.Color(255, 255, 255));
        mostrarButtom.setText("MOSTRAR");
        mostrarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarButtomActionPerformed(evt);
            }
        });
        jPanel2.add(mostrarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 150, 50));

        eliminarButtom.setBackground(new java.awt.Color(0, 102, 255));
        eliminarButtom.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        eliminarButtom.setForeground(new java.awt.Color(255, 255, 255));
        eliminarButtom.setText("ELIMINAR");
        jPanel2.add(eliminarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 150, 50));

        actualizarButtom.setBackground(new java.awt.Color(0, 102, 255));
        actualizarButtom.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        actualizarButtom.setForeground(new java.awt.Color(255, 255, 255));
        actualizarButtom.setText("ACTUALIZAR");
        jPanel2.add(actualizarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 150, 50));

        insertarButtom.setBackground(new java.awt.Color(0, 102, 255));
        insertarButtom.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        insertarButtom.setForeground(new java.awt.Color(255, 255, 255));
        insertarButtom.setText("INSERTAR");
        insertarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarButtomActionPerformed(evt);
            }
        });
        jPanel2.add(insertarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 150, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirButtomActionPerformed

    private void mostrarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarButtomActionPerformed

    private void insertarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertarButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualizarButtom;
    public javax.swing.JButton eliminarButtom;
    public javax.swing.JButton insertarButtom;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JButton mostrarButtom;
    public javax.swing.JButton salirButtom;
    // End of variables declaration//GEN-END:variables
}
